.github/workflows/codespell.yml
pkg/util/util.go

/kind test
test: add codespell github action
Fixes #
```
none
```

test: add codespell github action

---

Makefile
deploy/example/azurelustre/storageclass.yaml
pkg/azurelustreplugin/Dockerfile
pkg/azurelustreplugin/entrypoint.sh
test/integration_aks/image/run_integration_test.sh

/kind feature
Install Lustre client packages using apt install, rather than downloading from Azure blob container
Fixes #
```
none
```

Install Lustre client packages using apt install

---

test/external-e2e/run.sh
test/external-e2e/test_claim.yaml

/kind test
Add an e2e test to confirm CSI can delete volume after claim is deleted in default delete reclaim policy.
Fixes #
```
none
```

[test] add reclaim policy test

---

deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

/kind bug
Fixes #
```
none
```

[fix] fix log level argument

---

hack/boilerplate/boilerplate.py
hack/verify-integration-test-aks.sh
pkg/azurelustreplugin/entrypoint.sh
test/integration_aks/image/Dockerfile
test/integration_aks/image/run_integration_test.sh
test/ior/Dockerfile
test/ior/setup.sh
test/ior/test.sh

Add some file headers.
Fixes #
```
none
```

[fix] add copyright info

---

deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

/kind api-change
Install CSI images from MCR instead of private ACR
Fixes #
```
none
```

Install CSI images from MCR

---

test/ior/Dockerfile

/kind api-change
Clone IOR repo with tag 3.3.0
Fixes #
```
none
```

Clone IOR repo with tag 3.3.0

---

README.md
docs/README.md
docs/csi-debug.md
docs/csi-dev.md
docs/install_csi_driver.md
docs/static_provisioning.md

Modify documentation
Fixes #
```
none
```

[Doc] Modify documentation and add troubleshooting guidance

---

deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml
go.mod
pkg/azurelustreplugin/main.go

/kind cleanup
disable the unused metrics server.
Fixes #
```
none
```

[chore] disable the unused metrics server

---

pkg/azurelustre/azurelustre.go
pkg/azurelustre/nodeserver.go

/kind bug
OS sometime will crash when doing umount parallel to Lustre Volume. So, add a lock to serialize the mount/umount option.
Fixes #
```
none
```

[fix] add mount umount lock to fix crash problem

---

.github/workflows/long_haul.yaml
deploy/example/azurelustre/storageclass.yaml
test/long-haul/sample-workload/deployment_write_print_file.yaml
test/long-haul/start-long-haul.sh

/kind test
Add secrets for Long-haul test
Fixes #
```
none
```

Add secrets for Long-haul test

---

test/long-haul/sample-workload/deployment_write_print_file.yaml
test/long-haul/utils.sh

/kind test
minor changes to long-haul
mds -> mgs 
remove sample workload before deploying it
Fixes #
```
none
```

minor changes to long-haul 

---

deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml
pkg/azurelustreplugin/entrypoint.sh

Specify Lustre Version in deploy yaml

---

CONTRIBUTING.md

Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #56

Fixes the issue of broken link

---

pkg/azurelustreplugin/entrypoint.sh

feature
Modify entrypoint.sh to support Lustre version 2.15.1
Fixes #
```
none
```

Support Lustre 2.15.1

---

README.md
deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

feature
Use Release 0.1.3 CSI Image
Fixes #
```
none
```

Use Release 0.1.3 CSI Image

---

deploy/install-driver.sh
test/long-haul/fault-test.sh
test/long-haul/sample-workload/deployment_write_print_file.yaml
test/long-haul/start-long-haul.sh
test/long-haul/update-test.sh
test/long-haul/utils.sh

test
Improve fault and update test
Fixes #
```
none
```

[Test] Improve fault and update test

---

test/external-e2e/run.sh
test/long-haul/external-e2e.sh
test/long-haul/start-long-haul.sh

/kind bug
fix the errors of external e2e test
Fixes #
```
none
```

[fix] fix the errors of external e2e test

---

test/external-e2e/.gitignore
test/external-e2e/e2etest_storageclass.yaml
test/external-e2e/e2etest_storageclass.yaml.template
test/external-e2e/run.sh
test/long-haul/external-e2e.sh

/kind test
Updating external E2E test version to match AKS version.
Fixes #
```
none
```

[test] Updateing external E2E test version

---

test/long-haul/update-test.sh

/kind test
Modify 'update test case'
Fixes #
```
none
```

Modify 'update test case'

---

deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml
deploy/example/echodate/storageclass.yaml
pkg/azurelustreplugin/Dockerfile
pkg/azurelustreplugin/entrypoint.sh

/kind feature
Support Ubuntu 22.04
Fixes #
```
none
```

Support Ubuntu 22.04

---

OWNERS

Add vinli-cn as Owner

---

test/scale/run_test.py

/kind test
Let perf/scale test installs local CSI driver instaed of public one. So that, test pipeline can change the CSI image to a private one.
Fixes #
```
none
```

[test] Let perf/scale test installs local CSI driver.

---

README.md

Update document for v0.1.4

---

deploy/install-driver.sh
test/external-e2e/run.sh

[test] fix csi local installation path

---

test/external-e2e/run.sh
test/long-haul/external-e2e.sh

/kind test
Fixes #
```
none
```

[test] change parameters to supplsupport go 2.0

---

.github/workflows/static.yaml

/kind test
Fixes #
```
none
```

[test] fix go lint

---

OWNERS

[chore] add ownership

---

.github/workflows/codeql-analysis.yml
.github/workflows/darwin.yaml
.github/workflows/external_e2e.yaml
.github/workflows/integration_test_aks.yaml
.github/workflows/linux.yaml
.github/workflows/sanity_test_local.yaml
deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml
pkg/azurelustreplugin/entrypoint.sh

Update to use metapkg and distro-specific repo.
Promote go versions to 1.19.
Increase initial CSI startup timeout.
/kind bug
Fixes #90 
```
none
```

Update to use metapkg and distro-specific repo.

---

.github/workflows/static.yaml
.github/workflows/trivy.yaml
README.md
deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

release v0.1.5

---

test/long-haul/update-test.sh
test/long-haul/utils.sh

test
Update new client module package name
Increase timeout 
Fixes #
```
none
```

Update longhaul for v0.1.5 image

---

deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

Update CSI driver ports

---

.gitignore
deploy/csi-azurelustre-node.yaml
deploy/example/echodate/deployment.yaml
pkg/azurelustreplugin/Dockerfile
pkg/azurelustreplugin/entrypoint.sh
pkg/azurelustreplugin/fix-lnet.sh

/kind bug
Fixes #
```
none
```

[bug] fix lnet

---

pkg/azurelustreplugin/entrypoint.sh

[bug] fix update

---

README.md
deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

update document & deploy script for v0.1.7

---

pkg/azurelustreplugin/fix-lnet.sh

/kind bug
Fixes #
```
none
```

[bug] add dely and retry as workaround

---

README.md
deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

Bump up to v0.1.8

---

Makefile
pkg/driverinstaller/Dockerfile_mariner2
pkg/driverinstaller/Dockerfile_ubuntu1804
pkg/driverinstaller/Dockerfile_ubuntu2204

/kind feature
Modify makefile to support installer images
Fixes #
```
none
```

Modify makefile to support installer images

---

hack/verify-integration-test-aks.sh
test/integration_aks/image/run_integration_test.sh

/kind test
Fixes #
```
none
```

Fix integration test workflow

---

pkg/azurelustreplugin/Dockerfile

Fix CVE-2022-3821

---

pkg/azurelustreplugin/entrypoint.sh
pkg/azurelustreplugin/fix-lnet.sh
test/long-haul/perf-scale-test.sh

/kind feature
Check lnet issue every 0.5 secs
Exit fast if lnet has been fixed
Fixes #
```
none
```

Improve fix-lnet.sh

---

test/long-haul/perf-scale-test.sh

/kind bug
Fixes #
```
none
```

Fix per-scale-test

---

test/long-haul/perf-scale-test.sh

/kind bug
Fixes #
```
none
```

remove useless space

---

pkg/azurelustreplugin/entrypoint.sh
pkg/azurelustreplugin/fix-lnet.sh
test/long-haul/perf-scale-test.sh
test/long-haul/start-long-haul.sh

/kind cleanup
Fixes #
```
none
```

Link issue #115 fix lnet in code

---

deploy/install-driver.sh

Fix url in install

---

deploy/install-driver.sh

Support tag in install.sh

---

.github/workflows/long_haul.yaml
deploy/example/echodate/storageclass.yaml

/kind test
Fixes #
```
none
```

Disable long-haul on GH

---

test/long-haul/start-long-haul.sh

/kind test
Fixes #
```
none
```

Disable E2E test in long-haul pipeline due to LNET issue

---

.github/workflows/integration_test_aks.yaml

/kind test
Fixes #
```
none
```

Run integration test only when tag saftetorun added

---

README.md
deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

Use the new 0.1.11 version
Fixes #
```
none
```

Bump up to version 0.1.11

---

pkg/azurelustre/controllerserver_test.go

The parameters in the request do not have a guaranteed order. So, in one test, the regex assertion would fail if the invalid parameters were not listed in the original order. Since we do not care what order the error reports the parameters in, this commit changes the assertion only to ensure the expected unique values are present in the error.
/kind test
Fixes #
```
none
```

Fix flaky test

---

pkg/azurelustreplugin/entrypoint.sh
test/integration_aks/image/run_integration_test.sh

/kind feature
Bumps to a new version of the lustre client
Fixes #
```
none
```

Bump to 2.15.1-33-g0168b83

---

deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

/kind feature
Updates deployment files with the new image
Fixes #
```
none
```

Updating deployment files to new CSI image

---

deploy/csi-azurelustre-controller.yaml

The role name in kubernetes is 'control-plane'. Other drivers still have the un-hyphenated version, so this commit does not remove that, but adds the correct role as expected.
Fixes #
```
none
```

Add correct control-plane toleration value

---

deploy/csi-azurelustre-controller.yaml
test/external-e2e/e2etest_storageclass.yaml.template
test/long-haul/cleanup/cleanupjob.yaml
test/long-haul/sample-workload/deployment_write_print_file.yaml

This change went in with the sub-dir changes, but it requires the new image for the driver to function properly. We need to change this value back until we can update the deployment files to use a new driver image. As it is, the dynamic volume creation fails because the extra metadata is being passed to a controller that is not yet expecting it.
Commenting out sub-dir references in tests for similar reasons.
/kind bug
Fixes #
```
none
```

Revert metadata change until release image is available

---

OWNERS

What this PR does / why we need it:
Adding user dabradley to reviewer and approver ownership, now that I have k8s-sig membership.
https://github.com/kubernetes/org/issues/4668
Fixes #
```
none
```

Add dabradley to repo owners

---

Makefile
deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml
docs/examples/pod_echo_date_subdir.yaml
docs/examples/pv_subdir.yaml
docs/examples/pvc_pv_subdir.yaml
docs/examples/pvc_storageclass_subdir.yaml
docs/examples/storageclass_existing_lustre_subdir.yaml
test/external-e2e/e2etest_storageclass.yaml.template
test/long-haul/cleanup/cleanupjob.yaml
test/long-haul/sample-workload/deployment_write_print_file.yaml

/kind feature
Enables subdir mounts in various templates. Also bumps lustre client version to 2.15.3-43-gd7e07df
Fixes #
```
none
```

Bump to v0.1.14 with the 2.15.3 lustre clients and subdir mounts enabled

---

deploy/install-driver.sh
go.mod
go.sum
pkg/azurelustreplugin/entrypoint.sh
vendor/github.com/golang/protobuf/jsonpb/decode.go
vendor/github.com/golang/protobuf/jsonpb/encode.go
vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go
vendor/github.com/golang/protobuf/ptypes/any.go
vendor/modules.txt

/kind feature
/kind regression
Migrating integrated lustre client from 2.15.3 to 2.15.4 for Security/compatibility.  
Also cleaning up documentation, fixing a go-dep, and hardening the user-facing install script.
Fixes #
```
none
```

2.15.4 Client Upgrade - Container + deps

---

test/scale/run_test.py

/kind test
Updating Perf Scale test to use new `install-driver.sh` format.
Fixes #
```
none
```

Cleanup local CSI installation in local automated perf scale test.

---

test/long-haul/utils.sh
test/scale/run_test.py

/kind bug
Fixes some issues causing longhaul tests to fail on a fresh AKS cluster.
Fixes #168 
```
none
```

Fix longhaul tests when running on fresh cluster

---

.github/workflows/codeql-analysis.yml
.github/workflows/codespell.yml
.github/workflows/darwin.yaml
.github/workflows/external_e2e.yaml
.github/workflows/integration_test_aks.yaml
.github/workflows/linux.yaml
.github/workflows/sanity_test_local.yaml
.github/workflows/static.yaml
.github/workflows/trivy.yaml
.github/workflows/windows.yaml
go.mod
go.sum
pkg/csi-common/controllerserver-default.go

The existing workflows are out of date and insecure. This change updates the relevant workflows to the
current state of the repository, corrects some issues, and disables workflows that will be handled through other means.

Correct and update workflows so we can enable Actions

---

.github/workflows/codeql-analysis.yml
.github/workflows/linux.yaml
go.sum
hack/verify-golint.sh
pkg/csi-common/utils_test.go

Fix minor workflow issues

---

OWNERS

/kind cleanup
Add me to owners in dev branch as well
Fixes #
```
none
```

Add t-mialve to owners

---

.github/workflows/trivy.yaml

/kind test
Enables running the trivy scan on the development branch

Run trivy on development branch as well

---

README.md
deploy/csi-azurelustre-node.yaml
pkg/azurelustreplugin/entrypoint.sh

/kind feature
Bumps client to 2.15.5-41-gc010524
Fixes #
```
none
```

Bump client to 2.15.5

---

Makefile
README.md
deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

/kind feature
Bumps default image to v0.1.16
Fixes #
```
none
```

Bump image to v0.1.16

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/modules.txt

Upgrade jwt

---

OWNERS

/kind cleanup
Remove old maintainers from the owners file.
Fixes #
```
none
```

t-mialve/update owners

---

go.mod
go.sum
vendor/golang.org/x/net/html/doc.go
vendor/golang.org/x/net/html/doctype.go
vendor/golang.org/x/net/html/foreign.go
vendor/golang.org/x/net/html/iter.go
vendor/golang.org/x/net/html/node.go
vendor/golang.org/x/net/html/parse.go
vendor/golang.org/x/net/http2/client_conn_pool.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/net/http2/unencrypted.go
vendor/modules.txt

Upgrade golang.org/x/net

---

Makefile
README.md
deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

/kind feature
Update to new pod image
Fixes #
```
none
```

Bump to v0.1.17 image

---

README.md
docs/driver-parameters.md
docs/dynamic-provisioning.md
docs/examples/storageclass_dynprov_lustre.yaml
docs/examples/storageclass_existing_lustre.yaml
docs/install-csi-driver.md
docs/static-provisioning.md
pkg/azurelustre/azurelustre_test.go
pkg/azurelustre/controllerserver.go
pkg/azurelustre/controllerserver_test.go
pkg/azurelustre/dynamic_provisioning.go
pkg/azurelustre/dynamic_provisioning_test.go

Updates for dynamic provisioning

---

Makefile
README.md
deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

Bump image to v0.1.18

---

Makefile
deploy/csi-azurelustre-node.yaml
go.mod
go.sum
pkg/azurelustreplugin/Dockerfile
pkg/azurelustreplugin/entrypoint.sh
vendor/github.com/golang-jwt/jwt/v5/README.md
vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
vendor/github.com/golang-jwt/jwt/v5/parser.go
vendor/github.com/golang-jwt/jwt/v5/token.go
vendor/modules.txt

Modifies the makefile and controller so that we can build it with Dalec
Fixes #
```
none
```

Prep for Dalec builds

---

Makefile

Remove GOARCH var for dalec builds
Fixes #
```
none
```

Remove GOARCH var from azurelustre-dalec build

---

README.md
deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml
docs/csi-debug.md

Bumps to new image version
Fixes #
```
none
```

Bump to v0.2.0 image

---

test/integration_dalec/run_integration_test.sh

/kind feature
Remove the lctl command since we don't have the client installed in here, and pin to the latest version of csc that supports  go 1.23
Fixes #
```
none
```

Pin csc for dalec integration tests

---

README.md
docs/csi-debug.md
docs/driver-parameters.md
docs/dynamic-provisioning.md
docs/errors.md
docs/examples/pod_echo_date_dynprov.yaml
docs/examples/pvc_storageclass_dynprov.yaml
docs/examples/storageclass_dynprov_lustre.yaml
docs/install-csi-driver.md
pkg/azurelustre/azurelustre.go
pkg/azurelustre/azurelustre_test.go
pkg/azurelustre/controllerserver.go
pkg/azurelustre/controllerserver_test.go
pkg/azurelustre/dynamic_provisioning.go
pkg/azurelustre/dynamic_provisioning_test.go
pkg/azurelustreplugin/main.go
support.md

To ease the adoption of Dynamic Provisioning, we are adding documentation regarding common error cases and methods of debugging and resolving issues.
To ease the adoption of Dynamic Provisioning, we are adding documentation regarding common error cases and methods of debugging and resolving issues.
Fixes #
```
none
```

Add debug documentation

---

Makefile
deploy/csi-azurelustre-controller.yaml
deploy/csi-azurelustre-node.yaml

Use upstream image for testing

---

go.mod
hack/verify-golint.sh
test/integration_dalec/integration_dalec_aks.yaml.template
test/integration_dalec/run_integration_test.sh
test/integration_dalec/setup_integration_test_dalec.sh

Unpin golang version
