deploy/install-driver.sh, docs/install-csi-driver.md
/kind feature
Enable remote install
Fixes #
```
none
```
=> Enable CSI Driver Remote Install

deploy/csi-azurelustre-node.yaml
/kind feature
Map host paths to daemonset pods for IOPS improvements
Fixes #
```
none
```
=> Map host paths to daemonset pods for IOPS improvements

OWNERS
Adding user joe-atzinger to reviewer and approver ownership, now that I have k8s-sig membership.
https://github.com/kubernetes/org/issues/4308
=> Add joe-atzinger to repo owners.

pkg/azurelustreplugin/entrypoint.sh
This commit explicitly loads the ksocklnd module and configures the skip_mr_route_setup setting. This setup is not required for correct Lnet behavior, and breaks the network routing on AKS clusters with CNI networking. With this change, this now deploys, mounts, and connects correctly in both kubenet and cni configurations.
/kind bug
This commit explicitly loads the ksocklnd module and configures the skip_mr_route_setup setting. This setup is not required for correct Lnet behavior, and breaks the network routing on AKS clusters with CNI networking. With this change, this now deploys, mounts, and connects correctly in both kubenet and cni configurations.
Fixes #132  …
=> Skip routing rules when configuring ksocklnd

test/external-e2e/run.sh
The Kubernetes clusters we run our e2e tests against do not have the ReadWriteOncePod feature enabled by default. The test suite has changed to run these tests against the alpha / beta supported versions of this feature. This commit continues to skip these tests until we are actively testing against Kubernets 1.27+ where this feature is enabled by default.
/kind test
The Kubernetes clusters we run our e2e tests against do not have the ReadWriteOncePod feature enabled by default. The test suite has changed to run these tests against the alpha / beta supported versions of this feature. This commit continues to skip these tests until we are actively testing against Kubernets 1.27+ where this feature is enabled by default. …
=> Skip ReadWriteOncePod e2e tests

pkg/azurelustreplugin/entrypoint.sh
Bug
In addition to check /etc/apt/sources.list.d/amlfs.list exists we need to check if the apt-update is successful. This will help us recover the pod in-case of restarts during apt-update or failure in apt-update there by not leading the pod in an irrecoverable state.
Issue  https://github.com/kubernetes-sigs/azurelustre-csi-driver/issues/141
=> Changes to entrypoint for better resilience

Makefile, pkg/azurelustreplugin/main.go
/kind cleanup
Fixes the location of the logtostderr flag to avoid go panics and bumps the CSI version to 0.1.12
Fixes #
```
none
```
=> Minor go fix and CSI version bump to 0.1.12

deploy/csi-azurelustre-node.yaml, pkg/azurelustreplugin/entrypoint.sh
We currently don't have a supported in-place upgrade path for users because of the way our packages are configured. There are a number of ways that the installed packages can get into bad states that apt (and even dpkg directly) refuses to work around without manual intervention.
To avoid this behavior, this commit adds limited retries to the package installation step that, in the instance of a failed client install, will attempt to unload any running Lustre modules, remove the installed packages, and retry the installation.
In addition, when the pod is terminated, it will attempt to unload the Lustre modules, but will not fail if it cannot unload them (such as when there are existing pods running which have active Lustre mounts).
If it cannot unload the existing modules, it will log a …
=> Uninstall existing driver if upgrade fails

deploy/csi-azurelustre-controller.yaml, docs/examples/pod_echo_date_subdir.yaml, docs/examples/pv_subdir.yaml, docs/examples/pvc_pv_subdir.yaml, docs/examples/pvc_storageclass_subdir.yaml, docs/examples/storageclass_existing_lustre_subdir.yaml, pkg/azurelustre/azurelustre.go, pkg/azurelustre/controllerserver.go, pkg/azurelustre/controllerserver_test.go, pkg/azurelustre/fake_mount.go, pkg/azurelustre/fake_mount_test.go, pkg/azurelustre/identityserver_test.go, pkg/azurelustre/nodeserver.go, pkg/azurelustre/nodeserver_test.go, pkg/azurelustre/version_test.go, pkg/azurelustreplugin/main.go, pkg/csi-common/driver.go, pkg/csi-common/driver_test.go, pkg/csi-common/server_test.go, pkg/csi-common/utils_test.go, pkg/util/util_test.go, test/external-e2e/e2etest_storageclass.yaml.template, test/long-haul/cleanup/cleanupjob.yaml, test/long-haul/sample-workload/deployment_write_print_file.yaml
This commit adds the ability for pods to bind to a Lustre volume in a specified subdirectory. The pod that binds the volume in this way can only see that path and the paths under it. It has no access or visibility to other paths above it in the Lustre filesystem.
This has been implemented similarly to other CSI drivers to meet user expectations, but has the added benefit of allowing the user to leverage metadata from both the pvc/pv metadata and the pod's metadata as well.
Numerous checks have been put in place to ensure that data outside of the requested subdirectory is not deleted and that read only volumes are handled reasonably.
The long-haul tests have had compatible subdirectory values set to exercise this functionality while still maintaining its expectations as to data …
=> Add sub-dir functionality

pkg/azurelustre/nodeserver.go, pkg/azurelustre/nodeserver_test.go, test/scale/run_test.py, test/scale/static_workload.yml.template
Locking at the volume level was necessary for the original proof of concept that used stage/unstage steps with a global path. However, with the lock being used per-publish/unpublish step, it was causing unnecessary slowdowns when many pods were created or deleted for a given volume. This commit changes the behavior to lock only for a specific pod's directory, which will avoid this delay across individual pods for a single volume.
/kind bug 
Fixes #
```
none
```
=> Correct per-publish/unpublish lock

docs/examples/pv_subdir.yaml, pkg/azurelustre/nodeserver.go, pkg/azurelustre/nodeserver_test.go
The only reasonable way that the unpublish command can determine whether to keep or delete the subdirectory, if given, is to bake this information into the volume ID, as the original volume context is not passed to volume unpublish calls. For dynamically created volumes, this is always consistent. However, if the end user defines their own volumes, but does not follow the expected volume handle / volume ID form, that information is not available. In this instance, if the user sets the retain-sub-dir value on a manually created volume to 'false', we will error out and refuse to create the volume. If they request that the subdirectory be retained, we will treat the volume as we do a read-only volume, where we will attempt to mount the given subdirectory, but will not do any logic associated …
=> Skip subdirectory creation for invalid volume ID

docs/examples/pv_subdir.yaml, docs/examples/storageclass_existing_lustre_subdir.yaml, pkg/azurelustre/azurelustre.go, pkg/azurelustre/controllerserver.go, pkg/azurelustre/controllerserver_test.go, pkg/azurelustre/nodeserver.go, pkg/azurelustre/nodeserver_test.go, test/external-e2e/e2etest_storageclass.yaml.template, test/long-haul/cleanup/cleanupjob.yaml, test/long-haul/sample-workload/deployment_write_print_file.yaml, test/scale/static_workload.yml.template
The retain-sub-dir feature is intended to allow the user to have their subdirectory data automatically cleaned up when a pod unmounts from the Lustre filesystem. However, based on test, in its current form it allows the user to easily get themselves into a bad state or to lose data. For this release, we will maintain the subdirectory creation and mounting logic, but will wait on any customer feedback before re-enabling this functionality based on expected use cases.
/kind bug
Fixes #
```
none
```
=> Remove retain-sub-dir option

Makefile, README.md, deploy/csi-azurelustre-controller.yaml, deploy/csi-azurelustre-node.yaml, docs/install-csi-driver.md
Add one of the following kinds:
/kind feature
Moving CSI from v0.1.14 to v0.1.15.  Includes 2.15.4 client as well as a few Security/cleanup patches.
Fixes #
```
* 2.15.4 Lustre Client
* install-driver.sh refactor
* Misc CVE/Doc fixes.
```
=> Defaulting to v0.1.15 CSI 

pkg/azurelustreplugin/entrypoint.sh
/kind bug
Skips interfaces that are in an UNKNOWN state. If these aren't skipped it may cause extra client IPs to be added.
Fixes #
```
none
```
=> Add skip for interfaces in unknown state to entrypoint script

pkg/azurelustre/controllerserver_test.go
/kind test
Fixes #
```
none
```
=> Fix testing

pkg/azurelustre/azurelustre.go, pkg/azurelustre/fake_mount.go, pkg/azurelustre/nodeserver.go, pkg/azurelustre/nodeserver_test.go
There have been cases where the logic to cleanup a mount point has caused the driver to get into a bad state. This is most obvious when a subdirectory is mounted to a volume and a parent directory of that subdirectory is deleted. The Lustre driver doesn't handle that case in the way that Kubernetes expects and returns invalid data. To avoid this scenario causing our driver to get into a bad state, leak mount points, etc, we must explicitly check that we can read the necessary information about the mount point, and if not, explicitly unmount that mount point before allowing Kubernetes to clean up the directory. To ensure that we don't end up in a bad state, this change enables force unmounting as well. The force unmount will only occur after a timeout has expired, since force unmounts can …
=> Use force unmount and explicitly unmount bad mount points

deploy/csi-azurelustre-driver.yaml
In order to be able to use non-root accounts, it is important for the driver to allow k8s to change group ids in the cluster. Adding this value enables this ability so that in all circumstances, a pod can run with the expected filesystem group ACLs set.
Fixes #
```
none
```
=> Add fsGroupPolicy to driver

go.mod, test/integration_dalec/integration_dalec_aks.yaml.template, test/integration_dalec/run_integration_test.sh, test/integration_dalec/setup_integration_test_dalec.sh
Add an integration test specifically for dalec
Fixes #
```
none
```
=> Add dalec integration testing

test/external-e2e/e2etest_storageclass.yaml.template, test/external-e2e/run.sh, test/external-e2e/testdriver-azurelustre.yaml, test/long-haul/sample-workload/deployment_write_print_file.yaml, test/long-haul/start-long-haul.sh
=> Fix race condition in tests

deploy/csi-azurelustre-controller.yaml, deploy/csi-azurelustre-node.yaml
Change imagePullPolicy from IfNotPresent to Always in both CSI driver deployment manifests to ensure automatic pickup of new patch releases without requiring manual intervention.  Internal workitem https://msazure.visualstudio.com/One/_workitems/edit/33532215
Changes:
- deploy/csi-azurelustre-controller.yaml: azurelustre container
- deploy/csi-azurelustre-node.yaml: azurelustre container
/kind cleanup
This PR changes the `imagePullPolicy` from `IfNotPresent` to `Always` for the azurelustre CSI driver containers in both the controller and node deployments. This ensures that Kubernetes will automatically pull the latest container images when pods are created or restarted, allowing for automatic pickup of new patch releases …
=> Set ImagePullPolicy to Always for automatic patch updates
